name: strict_analyzer
description: The Dart analyzer settings with stricter linter rules that allow you to write more maintainable code and improve performance.
version: 0.2.1+2
homepage: https://github.com/vr19860507/strict_analyzer

environment:
  sdk: ">=2.8.1 <3.0.0"